### PR TITLE
Rebase and modify cloudbuild file

### PR DESCRIPTION
**Pull request by charlottehank**

### CODE REVIEW

**Comment by jojojames** [comment]
These commits seem off still.

If it's simpler, you can just pull the latest upstream master, and create a new branch based off that and then apply your changes.

**Comment by charlottehank** [comment]
> These commits seem off still.
> 
> If it's simpler, you can just pull the latest upstream master, and create a new branch based off that and then apply your changes.

Sorry, I think I just don't understand what's wrong with the commits. Is it that there's so many of them?

**Comment by jojojames** [comment]
You can have as many commits as you want as long as your commits can be applied on top of the branch you're trying to merge to.

The message is:

```
This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch. 
```

So I'm guessing your new commits are on top of a branch that is out of date with the main master branch/repo.

1 approach is to rebase your current branch on top of the main master branch repo and then re-push your branch. (Your PR's commits should now *all* be on top of the master branch so should be ok to merge.)

2nd approach is to create a new branch based off the latest master branch and then add your changes to that branch and create a new PR. If you do that, all your new changes will be on top of master (given you've just created a branch based off the latest master).

**Comment by charlottehank** [comment]
> You can have as many commits as you want as long as your commits can be applied on top of the branch you're trying to merge to.
> 
> The message is:
> 
> ```
> This branch cannot be rebased due to conflicts
> Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch. 
> ```
> 
> So I'm guessing your new commits are on top of a branch that is out of date with the main master branch/repo.
> 
> 1 approach is to rebase your current branch on top of the main master branch repo and then re-push your branch. (Your PR's commits should now _all_ be on top of the master branch so should be ok to merge.)
> 
> 2nd approach is to create a new branch based off the latest master branch and then add your changes to that branch and create a new PR. If you do that, all your new changes will be on top of master (given you've just created a branch based off the latest master).

Okay I will try the second approach. Gates said that my repo is already on the most recent rebase, and I can't find that error, but hopefully your second approach will solve the issue!

I see what the error is now. Thank you!

**Pull request closed without merging**
